---
- name: register example
  hosts: all 
  sudo: yes
 
  tasks:
    - name: stop service
      service: name=httpd state=started
      ignore_errors: True
      register: service_result
 
    - name: shutdown
      command: "shutdown -h +1m"
      when: service_result | failed
